mmzone.h: Fix warnings for unused variable
../include/linux/mmzone.h:1173:6: error: variable 'nid' set but not used
      [-Werror,-Wunused-but-set-variable]
 1173 |         int nid;
      |